Поднятие минимальной версии ios
azimin/CocoaHeadsMeetupApp pull request #358
Opened 2020-01-08 14:48 UTC by Ferrerohub

**Тема ревью**
С учетом статистики по использованию iOS 10 (<1%) и специфики целевой аудитории приложения, было решено поднять минимальную версию до 11
**Описание ревью**
Повышен deployment target на iOS 11, пофикшены всплывшие в связи с этим ворнинги

**На что обратить внимание и как тестировать**
Тестирование не требуется

**Связанные таски**

2020-01-09 19:13 UTC, anatoliykant requested changes

2020-01-09 19:13 UTC, anatoliykant commented on CHMeetupApp.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 11.0;
Если повышаешь версию, то минорную бери самую старшую - 11.4
В старших минорных версия закрыты дырки по безопасности.

2020-01-09 19:13 UTC, anatoliykant commented on CHMeetupApp.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 11.0;
тоже самое

2020-01-09 19:13 UTC, anatoliykant commented on CHMeetupApp.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 11.0;
тоже самое

2020-01-09 19:13 UTC, anatoliykant commented on CHMeetupApp.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 11.0;
тоже самое

2020-01-21 14:07 UTC, azimin approved these changes

2020-01-21 14:08 UTC, merged